### ISSUE TITLE
Создать UI

### ISSUE THREAD

**Issue by MaxTheFirst** [MaxTheFirst/matrix_calc#1]
Написать UI с помощью tkinter:
1. Выбор действия (найти определитель, найти обратную). 
2. Выбор порядка матрицы (22, 33).
3. При выборе появляется соответствующая таблица полей для ввода. 
4. Кнопка "Вычислить".
5. (Опционально) окно предпросмотра Latex.
6. Текстовое поле с кодом.
7. Кнопка "Копировать".

**Comment by Vadim-Zachesov** [comment]
Test

**Comment by vadimzachesov** [comment]
Добавил поддержку nxn матриц размерами от 2 до 25 вкл (по запросу)
